### ISSUE TITLE
USER STORY: User Profile Page View/Edit 

### ISSUE THREAD

**Issue by naisepaul** [naisepaul/PetLovers#8]
As a **registered user** I want to be able to **see my profile page** so that I can **update my information**

**Acceptance Criteria**

- As a registered user, When I log in to my account, Then I should be able to access my profile page.
-As a registered user and I am on my profile page, Then I should see my personal information such as username, email, and profile picture.
- As a registered user and I am on my profile page, When I update my information through the profile page, Then the changes should be saved and reflected on my profile.
- As a registered user and I am on my profile page, When I click on the "Edit Profile" button, Then I should be able to edit my information.
- As a registered user and I edit my information on the profile page, When I submit the updated information, Then the changes should be saved and applied to my profile, and I should receive a confirmation message.

**Tasks:**
 Define th

- [ ] e profile url
- [ ]  Create the view that renders the profile page.
- [ ]  Create the option to edit the profile with prefilled details.
- [ ]  Create the view that handles the edit form.
- [ ]  Ensure there is an edit button on the profile page.
